config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :attendees
    resources :events, param: :slug
    resources :invitations
    resources :profiles
    resources :teams
    resources :users
    resources :questions
    resources :reviews
    resources :locations
    resources :badges
    resources :notifications
    get 'events/:order' =>'events#index',  as: 'events/asc'
    get 'locations/:order' =>'locations#index',  as: 'locations/asc'
    get 'attendees/:order' =>'attendees#index',  as: 'attendees/asc'
    get 'teams/:order' =>'teams#index',  as: 'teams/asc'
    get 'profiles/:order' =>'profiles#index',  as: 'profiles/asc'
    get 'users/:order' =>'users#index',  as: 'users/asc'
    get 'badges/:order' =>'badges#index',  as: 'badges/asc'
    get 'notifications/:order' =>'notifications#index',  as: 'notifications/asc'
    get 'notifications/new/:event_id', to: 'notifications#new', as: 'notifications/event'
    get 'badges/new/:event_id', to: 'badges#new', as: 'badges/event'

    # get 'updated_at', to: 'badge#updated_at', as: 'update'

    root to: 'attendees#index'
  end
  namespace :api do
    resources :badges
    root to:'badges#index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'privacy-policy', to: 'pages#privacy'
  # get 'auth/failure', to: redirect('/')
  get 'logout', to: 'sessions#destroy', as: 'logout'
  # get 'login', to: 'identities#login', as: 'login'
  get 'login', to: 'sessions#login', as: 'login'
  post 'login', to: 'sessions#create2'
  resources :users, only: [:show, :create, :edit, :update, :new]
  get 'user/invitations', to: 'users#invitations', as: 'invitations'
  post 'user/invitations/accept/:id' => 'users#accept_invite', as: 'accept_invitations'
  post 'user/invitations/reject/:id' => 'users#reject_invite', as: 'reject_invitations'

  root 'sessions#new'

  # printing stuff
  get 'print', to: 'printers#print'
  resources :events, only: :show, format: :js

  scope path: ':event', module: 'event', as: 'event' do
    root to: 'sessions#new', as: 'main'
    get 'logout', to: 'sessions#destroy', as: 'logout'
    get 'checkin', to: 'attendees#new', as: 'checkin'
    post 'checkin', to: 'attendees#create', as: 'post_checkin'
    get 'teams/draft', to: 'teams#draft', as: 'draft'
    get 'teams/select', to: 'teams#select', as: 'select'
    post 'teams/select/pick/:id' => 'teams#pick', as: 'pick_team'


    get 'login', to: 'sessions#login', as: 'login'
    get 'user/new', to: 'users#new', as: 'new_user'

  end

  # Serve websocket cable requests in-process
   # mount ActionCable.server => '/cable'
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :badge, dependent: :destroy
  attr_accessor :team_id
  attr_accessor :all
  attr_accessor :event_id
  enum weekday: [:monday, :tuestay, :wensday, :thursday, :friday, :saturday, :sunday]
  enum message_sent: [:inactivo, :color_rojo, :color_verde, :mensaje_cuatro, :mensaje_aqua, :mensaje_morado, :mensaje_amarillo]

  def message_int
    return self.read_attribute_before_type_cast(:message_sent)
  end
end

app/controllers/admin/notifications_controller.rb
module Admin
  class NotificationsController < Admin::ApplicationController
    before_action :set_notification, only: :destroy

    # GET /badge
    def index
      @notifications = Notification.all
      if params[:order]=="id"
        @notifications = Notification.all.order(id: :asc)
      elsif   params[:order]=="name"
        @notifications = Notification.all.sort_by{ |m| m.badge.attendee.user.name.downcase }
      end
    end

    def new
      @notification = Notification.new
      @events = Event.all
      @badges = Badge.all

      if(params[:event_id])
        @show_event = Event.find(params[:event_id].to_i)
        @notification = Notification.new(event_id:@show_event)
        @team =  Event.find(params[:event_id].to_i).teams
        @badges = Badge.all.select{|badge| badge.attendee.event.id == params[:event_id].to_i }
        @block = true
      else
        @show_event = nil
          @block = false
      end
    end
    # def new
    #   @notifications = []
    #   @badges = []
    #   # acabar esto mañana
    #   if params[:team_id]
    #     @team = Event.find(params[:event_id]).teams
    #   elsif params[:team_id] == "-1"
    #     attendees  =  Event.find(params[:event_id]).attendees
    #     @badges = attendees[0].find_badges(attendees)
    #     @badges.each do |badge|
    #       @notifications << Notification.new(badge_id: badge.id)
    #     end
    #   elsif params[:team_id].to_i >= 0 && params[:team_id]
    #     attendees = Team.find(params[:team_id]).attendees
    #     @badges = attendees[0].find_badges(attendees)
    #   else
    #     @badges =Badge.all
    #     @notifications << Notification.new
    #   end
    # end

    # POST /badge
    def create
      puts notification_params

      if(notification_params["team_id"])
      elsif notification_params["all"] == "1"
        attendees  = Attendee.all
            @badges = attendees[0].find_badges(attendees)
            @badges.each do |badge|
            save = Notification.new(badge_id: badge.id, message_sent: notification_params["message_sent"])
            save.save
            end

            if notification_params["team_id"].to_i >= 0
              attendees  =  Team.find(notification_params.team_id.to_i).attendees
              @badges = attendees[0].find_badges(attendees)
              @badges.each do |badge|
                save = Notification.new(badge_id: badge.id, message_sent: notification_params["message_sent"])
                save.save
              end
            end  

        else
            save = Notification.new(badge_id: notification_params["badge_id"].to_i, message_sent:  notification_params["message_sent"])
            save.save
      end
      redirect_to admin_notifications_path
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_notification
       @notification = Notification.find(params[:id])
     end

    # Only allow a trusted parameter "white list" through.
    def notification_params
      params.require(:notification).permit(:badge_id, :team_id, :event_id, :all, :message_sent)
    end
  end
end

app/views/admin/notifications/_form.html.erb
<%= form_for [:admin, @notification], html: { class: "form-horizontal article" } do |f| %>


      <div class="col-sm-10">

        <div class="dropdown">
          <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Events
          <span class="caret"></span></button>
          <ul class="dropdown-menu">
            <% @events.each do |event|%>
              <li><a><%= link_to event.name, new_admin_notification_path(event_id: event.id), class: "category" %></a></li>
            <%end%>
          </ul>
        </div>
      </div>
        <%unless @show_event.blank?%>
        <%= f.label :event, @show_event.name, class: 'col-12 form-control-label' %>
        <%end%>
          <div class="form-group row  m-4">
            <%= f.label :message_sent, 'Message', class: 'col-2 form-control-label float-left m-2' %>
            <div class="col-10">
              <%= f.select(:message_sent, Notification.message_sents.keys.map {|message_sent| [message_sent.upcase, message_sent]}, {}, class: 'col-9 m-2 float-left') %>
            </div>
          </div>

      <div class="form-group m-4">
        <%= f.label :badge_id , 'Select Badge', class: 'col-2 form-control-label float-left'%>
        <div class="col-lg-10">
            <%= f.collection_select :badge_id, @badges, :id, :names, class: 'form-control float-left' %>
        </div>
      </div>

    <div class="container">
      <%unless @team.blank? %>
      <%= f.label :team_id, 'Select a group', class: 'col-2 form-control-label' %>
      <div class="col-10">
        <%=  f.collection_select :team_id, @team, :id, :name, {}, class: 'form-control' %>
      </div>
    <%end%>
    </div>

    <div class=" m-4 row form-group">
      <%= f.label :all, 'Select all the badges', class: 'col-2 form-control-label float-left' %>
      <div class="form-check float-left">
        <%= f.check_box :all%>
      </div>
    </div>
    <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
          <%= f.submit nil, class: 'button' %>
          <%= link_to t('.cancel', default: t("helpers.links.cancel")),
                    admin_notifications_path, class: 'button' %>
        </div>
      </div>

  <%end%>

app/views/admin/notifications/new.html.erb
  <div class="card container_edit">
<div class="page-header">
  <h1>New Notification</h1>
</div>
<%= render partial: 'form', locals: {edit: true} %>
</div>