config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :attendees
    resources :events, param: :slug
    resources :invitations
    resources :profiles
    resources :teams
    resources :users
    resources :questions
    resources :reviews
    resources :locations
    resources :badges
    resources :notifications
    get 'events/:order' =>'events#index',  as: 'events/asc'
    get 'locations/:order' =>'locations#index',  as: 'locations/asc'
    get 'attendees/:order' =>'attendees#index',  as: 'attendees/asc'
    get 'teams/:order' =>'teams#index',  as: 'teams/asc'
    get 'profiles/:order' =>'profiles#index',  as: 'profiles/asc'
    get 'users/:order' =>'users#index',  as: 'users/asc'
    get 'badges/:order' =>'badges#index',  as: 'badges/asc'
    get 'notifications/:order' =>'notifications#index',  as: 'notifications/asc'
    get 'notifications/new/:event_id', to: 'notifications#new', as: 'notifications/event'
    get 'badges/new/:event_id', to: 'badges#new', as: 'badges/event'

    # get 'updated_at', to: 'badge#updated_at', as: 'update'

    root to: 'attendees#index'
  end
  namespace :api do
    resources :badges
    root to:'badges#index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'privacy-policy', to: 'pages#privacy'
  # get 'auth/failure', to: redirect('/')
  get 'logout', to: 'sessions#destroy', as: 'logout'
  # get 'login', to: 'identities#login', as: 'login'
  get 'login', to: 'sessions#login', as: 'login'
  post 'login', to: 'sessions#create2'
  resources :users, only: [:show, :create, :edit, :update, :new]
  get 'user/invitations', to: 'users#invitations', as: 'invitations'
  post 'user/invitations/accept/:id' => 'users#accept_invite', as: 'accept_invitations'
  post 'user/invitations/reject/:id' => 'users#reject_invite', as: 'reject_invitations'

  root 'sessions#new'

  # printing stuff
  get 'print', to: 'printers#print'
  resources :events, only: :show, format: :js

  scope path: ':event', module: 'event', as: 'event' do
    root to: 'sessions#new', as: 'main'
    get 'logout', to: 'sessions#destroy', as: 'logout'
    get 'checkin', to: 'attendees#new', as: 'checkin'
    post 'checkin', to: 'attendees#create', as: 'post_checkin'
    get 'teams/draft', to: 'teams#draft', as: 'draft'
    get 'teams/select', to: 'teams#select', as: 'select'
    post 'teams/select/pick/:id' => 'teams#pick', as: 'pick_team'


    get 'login', to: 'sessions#login', as: 'login'
    get 'user/new', to: 'users#new', as: 'new_user'

  end

  # Serve websocket cable requests in-process
   # mount ActionCable.server => '/cable'
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :profile, required: false
  has_many :invitation
  has_many :accepted_invitations, -> { where(status: :accepted) }, class_name: 'Invitation'
  has_many :attendees
  has_many :events, through: :attendees

  has_many :reviewees, class_name: 'Review', foreign_key: 'reviewee_id'
  has_many :reviewers, class_name: 'Review', foreign_key: 'reviewer_id'
  has_many :questions, through: :reviewees,  dependent: :destroy
  attachment :image, content_type: ["image/jpeg", "image/png"]

  enum shirt_size: [:s, :m, :l, :xl]
  enum role: [:user, :admin]

  attachment :avatar, type: :image
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :password, presence:true, length: { minimum: 6 }, on: :create
  validates :password, length: {minimum: 5, maximum: 120}, on: :update, allow_blank: true
  has_secure_password

  def overall_rank
    reviewees.average(:stars)
  end

  def question_ranks
    ranks = []
    questions.each do |q|
      ranks << { stars: Review.where(reviewee: self, question: q).average(:stars), question: q.question }
    end
    ranks
  end

  # def remember
  #   self.remember_token = User.new_token
  #   update_attribute(:remember_digest, User.digest(remember_token))
  # end

  def picture_url
    return avatar_url unless avatar_id.blank?
    return image_url unless image_url.blank?
    'https://placehold.it/500x500?text=Profile+Picture'
  end

  def pending_invitations?
    invitations.where(status: :pending).count > 0
  end

  def self.from_omniauth(auth)
    existing_user = User.find_by(email: auth.info.email)
    current_event = Event.last # TODO DELETE
    if existing_user
      Invitation.find_or_create_by(event: current_event, user: existing_user)
      return existing_user
    end
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.name = auth.info.name
      user.image_url = auth.info.image
      user.oauth_token = auth.credentials.token
      user.invitations << Invitation.create(event: current_event)
      user.save!
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    before_action :set_user, only: [:update, :destroy, :edit]

    def index
      @users =  User.all
      if params[:order]=="name"
        @users = User.all.order(name: :asc)
      elsif params[:order]=="id"
        @users = User.all.order(id: :asc)
      elsif params[:order]=="email"
        @users = User.all.order(email: :asc)
      end
    end

    def new
      @user = User.new
    end

    def edit; end

    def update
      user_params.delete(:password) unless user_params[:password].present?
      if @user.update(user_params)
        redirect_to admin_users_path
      else
        render :edit
      end
    end

    def show; end

    def create
      @user = User.new(user_params)
      if @user.save
        flash.keep[:notice] = 'User was successfully updated.'
        event = Event.all.where('events.finishes_at >= ?', Date.today)
        event.each do |events|
          a = Invitation.new(user_id: @user.id, event_id: events.id)
          a.save
        end
        redirect_to admin_users_path
      else
        render :new
      end
    end

    def destroy
        @user.destroy
      flash.keep[:notice] = 'User was successfully deleted.'
      redirect_to admin_users_path, notice: 'User was successfully updated.'
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :shirt_size, :avatar, :profile_id)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update, :destroy, :edit]
  before_action :set_invite, only: [:accept_invite, :reject_invite]

  def edit
  end

  def show
    @invitations = Invitation.where(user_id: @user.id, status: 'pending')
    @invitations = @invitations.joins(:event).where('events.finishes_at >= ?', Date.today)
    @events = @user.events
  end

  def new
    @user = User.new
  end

  def accept_invite
    @invite.status= "accepted"
    attendee = Attendee.new(user_id: @invite.user_id, event_id: @invite.event_id)
    attendee.save
    @invite.save
    redirect_to user_path(id: @invite.user_id)
  end

  def reject_invite
    @invite.status= "rejected"
    @invite.save
    redirect_to user_path(id: @invite.user_id)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      event = Event.all.where('events.finishes_at >= ?', Date.today)
      event.each do |events|
        a = Invitation.new(user_id: @user.id, event_id: events.id)
        a.save
      end
      # log_in(@user)
      # remember(@user)
      redirect_to user_path(id: @user.id), notice: 'User was successfully created.'
    else
      flash[:alert] = 'No se pudo crear la cuenta'
      render :new
    end
  end

  def update
    user_params.delete(:password) unless user_params[:password].present?
    if current_user.update(user_params)
      redirect_to user_next_path, notice: 'Se actualizaron tus datos'
    else
      render :edit, notice: 'No se pudieron actualizar tus datos'
    end
  end

  def invitations
    if current_user.pending_invitations?
      @invitations = current_user.invitations.where(status: :pending)
    else
      redirect_to edit_user_path, notice: 'No tienes invitaciones pendientes.'
    end
  end

  private


  def user_params
    params.require(:user).permit(:name, :email, :password, :shirt_size, :avatar)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_invite
    @invite = Invitation.find(params[:id])
  end

  def user_next_path
    return invitations_path if current_user.pending_invitations?
    redirect_to @user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def submit_button_text
    return 'Continuar' if current_user.pending_invitations?
    'Actualizar'
  end
end

app/views/admin/users/_form.html.erb
<div class="avatar">
  <span class="plus">+</span>
</div>
<div class="card-block m-4">

  <%= form_for [:admin, @user] do |f| %>
    <div class="form-group row">
        <%unless @user.errors[:name].empty?%>
          name <%=@user.errors[:name][0]%>
        <script type="text/javascript">

        </script>
        <%end%>
      <%= f.label :name, 'Nombre', class: 'col-sm-2 form-control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name, class:'form-control' %>
      </div>
    </div>
    <div class="form-group row">
      <%unless @user.errors[:email].empty?%>
        Email <%=@user.errors[:email][0]%>
      <script type="text/javascript">

      </script>
      <%end%>
      <%= f.label :email, 'Email', class: 'col-sm-2 form-control-label' %>
      <div class="col-sm-10">
        <%= f.email_field :email, class:'form-control'%>
      </div>
    </div>
    <div class="form-group row">
      <%unless @user.errors[:password].empty?%>
        Password <%=@user.errors[:password][0]%>
      <script type="text/javascript">

      </script>
      <%end%>
      <%= f.label :password, class: 'col-sm-2 form-control-label' %>
      <div class="col-sm-10">
        <%= f.password_field :password, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group row">
      <%unless @user.errors[:shirt_size].empty?%>
        Shirt_size <%=@user.errors[:shirt_size][0]%>
      <script type="text/javascript">

      </script>
      <%end%>
      <%= f.label :shirt_size, 'Playera', class: 'col-sm-2 form-control-label' %>
      <div class="col-sm-10">
        <%= f.select(:shirt_size, User.shirt_sizes.keys.map {|shirt| [shirt.upcase, shirt]}, {}, class: 'c-select form-control') %>
      </div>
    </div>

      </div>
    <div class="row mb-4">
      <div class="col-sm-4 offset-sm-1">
        <%= f.submit nil, class:"btn btn-primary btn-block" %>
      </div>
      <div class="col-sm-4 offset-sm-1">
        <div class="actions"><%= link_to "Back", admin_events_path, class:"btn btn-secondary btn-block" %></div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/users/_formEdit.html.erb
<div class="avatar">
  <span class="plus">+</span>
</div>
<div class="card-block m-4">

  <%= form_for [:admin, @user], html: { class: "form-horizontal article" } do |f| %>
    <div class="form-group row">
        <%unless @user.errors[:name].empty?%>
          name <%=@user.errors[:name][0]%>
        <script type="text/javascript">

        </script>
        <%end%>
      <%= f.label :name, 'Nombre', class: 'col-sm-2 form-control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name, class:'form-control' %>
      </div>
    </div>
    <div class="form-group row">
      <%unless @user.errors[:email].empty?%>
        Email <%=@user.errors[:email][0]%>
      <script type="text/javascript">

      </script>
      <%end%>
      <%= f.label :email, 'Email', class: 'col-sm-2 form-control-label' %>
      <div class="col-sm-10">
        <%= f.email_field :email, class:'form-control'%>
      </div>
    </div>
    <div class="form-group row">
      <%unless @user.errors[:shirt_size].empty?%>
        Shirt_size <%=@user.errors[:shirt_size][0]%>
      <script type="text/javascript">

      </script>
      <%end%>
      <%= f.label :shirt_size, 'Playera', class: 'col-sm-2 form-control-label' %>
      <div class="col-sm-10">
        <%= f.select(:shirt_size, User.shirt_sizes.keys.map {|shirt| [shirt.upcase, shirt]}, {}, class: 'c-select form-control') %>
      </div>
    </div>

      </div>
    <div class="row mb-4">
      <div class="col-sm-4 offset-sm-1">
        <%= f.submit nil, class:"btn btn-primary btn-block" %>
      </div>
      <div class="col-sm-4 offset-sm-1">
        <div class="actions"><%= link_to "Back", admin_users_path, class:"btn btn-secondary btn-block" %></div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/users/edit.html.erb
<div class="card container_edit">
  <% content_for :title, "Perfil #{@user.name}" %>
  <%= render 'formEdit' %>
</div>

app/views/admin/users/new.html.erb
  <div class="card container_edit">
    <h1 class="m-4">New user</h1>
    <%= render 'form' %>
  </div>